title: PhaseDocs
description: Documentation for all things PhaseII
theme: just-the-docs
color_scheme: dark
favicon_ico: /public/favicon.png

url: https://docs.phaseii.network

aux_links:
  WebUI V2: https://phaseii.network
  WebUI V3 (beta): https://web3.phaseii.network
